// ! ==========================================================
// ! DO NOT EDIT THIS FILE MANUALLY!
// ! This file is automatically generated. Any changes made to this file
// ! will be overwritten the next time the code is generated.
// ! ==========================================================

import { SocketV1 } from "./socket/socket.sdk";
import { AuthV1 } from "./auth/auth.sdk";
import { UserV1 } from "./user/users.sdk";
import { NotificationV1 } from "./notification/notification.sdk";
import { VersionV1 } from "./version/version.sdk";

/**
 * ####  🏴‍☠️ List of {@link NabiiV1} modules 🏴‍☠️
 */
export const modulesV1 = <const>{
	/**
	 * 📦 {@link SocketV1} module 📦
	 * @since v1.0.0
	 */
	Socket: SocketV1,
	/**
	 * 📦 {@link AuthV1} module 📦
	 * @since v1.0.0
	 */
	Auth: AuthV1,
	/**
	 * 📦 {@link UserV1} module 📦
	 * @since v1.0.0
	 */
	User: UserV1,
	/**
	 * 📦 {@link NotificationV1} module 📦
	 * @since v1.0.0
	 */
	Notification: NotificationV1,
	/**
	 * 📦 {@link VersionV1} module 📦
	 * @since v1.4.0
	 */
	Version: VersionV1,
};
