// ! ==========================================================
// ! DO NOT EDIT THIS FILE MANUALLY!
// ! This file is automatically generated. Any changes made to this file
// ! will be overwritten the next time the code is generated.
// ! ==========================================================

import type { Platform } from "@v1/config";
import type { IGlobalTypes } from "@v1/types/nabii";
import type { ISocketTypes } from "./socket/socket";
import type { IAuthTypes } from "./auth/auth";
import type { IUserTypes } from "./user/user";
import type { IVersionTypes } from "./version/version";

/**
 * ####  ✨ List of {@link NabiiV1} `types` ✨:
 * - {@link Platform} (A shortcut of a type into {@link IGlobalTypes})
 * - {@link IGlobalTypes}
 * - {@link ISocketTypes}
 * - {@link IAuthTypes}
 * - {@link IUserTypes}
 * - {@link IVersionTypes}
 * ---------------------------
 * Do you have ideas or recommendations for improvement?
 *  * @author Ulysse Dupont -->
 *  [Email](mailto:ulyssedupont2707@gmail.com)
 *  | [Github](https://github.com/Dulysse)
 *  | [LinkedIn](https://www.linkedin.com/in/ulysse-dupont)
 */
export declare namespace INabiiV1 {
	export {
		Platform,
		IGlobalTypes,
		ISocketTypes,
		IAuthTypes,
		IUserTypes,
		IVersionTypes,
	};
}
